# Generated by Django 4.1.3 on 2022-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0002_alter_registration_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
