# Generated by Django 4.1.3 on 2022-12-09 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0006_order_dtls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_dtls",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 9, 14, 22, 2, 602741)
            ),
        ),
    ]
