# Generated by Django 4.1.3 on 2022-12-12 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0008_alter_order_dtls_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_dtls',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_dtls',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.registration'),
        ),
        migrations.AlterField(
            model_name='order_dtls',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 47, 5, 751273)),
        ),
    ]
