# Generated by Django 4.1.3 on 2022-12-12 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0010_alter_order_dtls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_dtls',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 53, 40, 212785)),
        ),
    ]
