# Generated by Django 4.1.3 on 2022-12-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0011_alter_order_dtls_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_dtls",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
